### ISSUE TITLE
Remove the 'Need to access the Portfolio tool' option from the 'reason for leaving' dropdown

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-opt-in-out#118]
'Need to access the Portfolio tool' is listed as an option in the 'Select the main reason you're leaving' dropdown. A client has pointed out, however, that the link to the portfolio tool has been placed back in the header saying...

> You already had to put “portfolio” back on the header section, yet when asking “main reason for returning” (to old version FT) you still have “Need to access the portfolio tool” as a reason!! Some-one is not paying attention.

**Comment by matthew-andrews** [comment]
:sweat_smile:
