### ISSUE TITLE
Is infinite loop worth fixing?

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/next-opt-in-out#152]
These,

`curl -IL -A 'Blackberry' http://www.ft.com/cms/s/0/918d5c56-031b-11e6-99cb-83242733f755.html`

`curl -IL -A 'Samsung' http://www.ft.com/cms/s/0/918d5c56-031b-11e6-99cb-83242733f755.html`

...end up in an infinite redirect loop because ft.com redirects mobile users agents to m.ft.com, which bounces to Next, which bounces back to ft.com without the `FT_SITE=NEXT` cookie.

Accepting cookies fixes the problem, Eg.

`curl -IL -A 'Samsung' -c cookies -b cookies http://localhost:3002/__m-dot-opt-in?referrer=/cms/s/0/918d5c56-031b-11e6-99cb-83242733f755.html`

Is this worth fixing? And is the best way to add `?ft_site=falcon` to the Next redirect to ft.com.

**Comment by georgecrawford** [comment]
This is becoming a problem for us trying to improve our AMP carousel appearance, and SEO in general. Google rejects some URLs because "Google couldn't follow your URL because it redirected too many times.”

**Comment by georgecrawford** [comment]
@matthew-andrews said:
> unknown error is probably an artefact of the fact to do a redirect in varnish you throw an error and then catch it and convert to 3xx

**Comment by wheresrhys** [comment]
not any more it's not
